# Generated by Django 4.0.5 on 2022-10-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websocket',
            old_name='user_websocket',
            new_name='username_websocket',
        ),
    ]
